// This file generated by imgp at 2021-06-28 15:15:57
#ifndef IMGN_H
#define IMGN_H

#define IMGN_LENGTH 34
#define IMGN_ARR_LENGTH 2
const unsigned int imgn[ IMGN_LENGTH ][ IMGN_ARR_LENGTH ] = {{31,},{28,},{32,},{12,},{13,},{29,},{1,},{22,},{14,},{19,},{34,},{26,},{27,},{6,},{23,},{3,},{24,},{4,},{7,},{21,},{15,},{5,},{16,},{9,},{11,},{2,},{35,},{30,},{8,},{10,},{33,},{25,},{20,},{17,18,},};

#endif // IMGN_H
