// This file generated by imgp at 2021-07-03 11:10:33
// n stands for Naming. Use this header to get named indices for textures generated by imgd
#ifndef IMGN_H
#define IMGN_H

#define IMGN_IMAGES_LENGTH 40
#define IMGN_TEXTURES_LENGTH 36
#define IMGN_ARR_LENGTH 4
const unsigned int imgn[ IMGN_TEXTURES_LENGTH ][ IMGN_ARR_LENGTH ] = {{33,},{17,},{1,},{38,},{20,},{35,},{37,},{28,},{29,},{40,},{34,},{14,},{3,},{9,},{4,},{36,},{18,19,},{22,23,24,25,},{32,},{15,},{39,},{16,},{30,},{6,},{12,},{10,},{26,},{2,},{21,},{8,},{11,},{5,},{13,},{31,},{7,},{27,},};

const char imgn_type[ IMGN_TEXTURES_LENGTH ] = "SSISSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS";

#define IMGN_Sstevepipes 0
#define IMGN_Slightrig 1
#define IMGN_Ifixedsysa 2
#define IMGN_Stend 3
#define IMGN_Smachinepanela 4
#define IMGN_Sstolb 5
#define IMGN_Stak 6
#define IMGN_Spowerunit 7
#define IMGN_Srigfan 8
#define IMGN_Swlrockwall 9
#define IMGN_Sstola 10
#define IMGN_Sinlaida 11
#define IMGN_Sancientb 12
#define IMGN_Sfactdoor 13
#define IMGN_Sancientc 14
#define IMGN_Ssubw 15
#define IMGN_Slwall 16
#define IMGN_Sme 17
#define IMGN_Sshwall 18
#define IMGN_Sinlaidb 19
#define IMGN_Stfront 20
#define IMGN_Sinlaidc 21
#define IMGN_Srigspot 22
#define IMGN_Search 23
#define IMGN_Shlconsoleb 24
#define IMGN_Sfactwall 25
#define IMGN_Snewroof 26
#define IMGN_Sancienta 27
#define IMGN_Smachinepanelb 28
#define IMGN_Sfactdeco 29
#define IMGN_Shlconsolea 30
#define IMGN_Sbasenew 31
#define IMGN_Shlsupport 32
#define IMGN_Srigwall 33
#define IMGN_Sewood 34
#define IMGN_Spfall 35

#endif // IMGN_H
