// This file generated by imgp at 2021-07-03 19:19:22
// n stands for Naming. Use this header to get named indices for textures generated by imgd
#ifndef IMGN_H
#define IMGN_H

#define IMGN_IMAGES_LENGTH 41
#define IMGN_TEXTURES_LENGTH 37
#define IMGN_ARR_LENGTH 4
const unsigned int imgn[ IMGN_TEXTURES_LENGTH ][ IMGN_ARR_LENGTH ] = {{39,},{31,},{35,},{34,},{10,},{40,},{13,},{29,},{3,},{6,},{7,},{30,},{5,},{1,},{18,},{27,},{16,},{14,},{28,},{15,},{19,20,},{41,},{33,},{8,},{38,},{2,},{4,},{17,},{36,},{11,},{32,},{9,},{23,24,25,26,},{12,},{37,},{22,},{21,},};

const char imgn_type[ IMGN_TEXTURES_LENGTH ] = "SSSSSSSSSSSSSESSSSSSSSSSSISSSSSSSSSSS";

#define IMGN_Stend 0
#define IMGN_Srigspot 1
#define IMGN_Sstola 2
#define IMGN_Sstevepipes 3
#define IMGN_Sfactdoor 4
#define IMGN_Stfront 5
#define IMGN_Shlconsoleb 6
#define IMGN_Spowerunit 7
#define IMGN_Sancienta 8
#define IMGN_Sbasenew 9
#define IMGN_Search 10
#define IMGN_Srigfan 11
#define IMGN_Sancientc 12
#define IMGN_Erock 13
#define IMGN_Slightrig 14
#define IMGN_Snewroof 15
#define IMGN_Sinlaidb 16
#define IMGN_Shlsupport 17
#define IMGN_Spfall 18
#define IMGN_Sinlaida 19
#define IMGN_Slwall 20
#define IMGN_Swlrockwall 21
#define IMGN_Sshwall 22
#define IMGN_Sewood 23
#define IMGN_Stak 24
#define IMGN_Ifixedsysa 25
#define IMGN_Sancientb 26
#define IMGN_Sinlaidc 27
#define IMGN_Sstolb 28
#define IMGN_Sfactwall 29
#define IMGN_Srigwall 30
#define IMGN_Sfactdeco 31
#define IMGN_Sme 32
#define IMGN_Shlconsolea 33
#define IMGN_Ssubw 34
#define IMGN_Smachinepanelb 35
#define IMGN_Smachinepanela 36

#endif // IMGN_H
