// This file generated by imgp at 2021-07-03 19:19:22
// s stands for Static. Use this header in imgc to make imge for imgd
#ifndef IMGS_H
#define IMGS_H

#define IMGS_LENGTH 41
const char *imgs[] = {
  "images/Erock.bmp",
  "images/Ifixedsysa.bmp",
  "images/Sancienta.bmp",
  "images/Sancientb.bmp",
  "images/Sancientc.bmp",
  "images/Sbasenew.bmp",
  "images/Search.bmp",
  "images/Sewood.bmp",
  "images/Sfactdeco.bmp",
  "images/Sfactdoor.bmp",
  "images/Sfactwall.bmp",
  "images/Shlconsolea.bmp",
  "images/Shlconsoleb.bmp",
  "images/Shlsupport.bmp",
  "images/Sinlaida.bmp",
  "images/Sinlaidb.bmp",
  "images/Sinlaidc.bmp",
  "images/Slightrig.bmp",
  "images/Slwall1.bmp",
  "images/Slwall2.bmp",
  "images/Smachinepanela.bmp",
  "images/Smachinepanelb.bmp",
  "images/Sme1.bmp",
  "images/Sme2.bmp",
  "images/Sme3.bmp",
  "images/Sme4.bmp",
  "images/Snewroof.bmp",
  "images/Spfall.bmp",
  "images/Spowerunit.bmp",
  "images/Srigfan.bmp",
  "images/Srigspot.bmp",
  "images/Srigwall.bmp",
  "images/Sshwall.bmp",
  "images/Sstevepipes.bmp",
  "images/Sstola.bmp",
  "images/Sstolb.bmp",
  "images/Ssubw.bmp",
  "images/Stak.bmp",
  "images/Stend.bmp",
  "images/Stfront.bmp",
  "images/Swlrockwall.bmp",
};

#endif // IMGS_H
