// This file generated by imgp at 2021-06-28 15:15:57
#ifndef IMGS_H
#define IMGS_H

#define IMGS_LENGTH 35
const char *imgs[] = {
  "images/Aancienta.bmp",
  "images/Aancientb.bmp",
  "images/Aancientc.bmp",
  "images/Abasenew.bmp",
  "images/Aearch.bmp",
  "images/Aewood.bmp",
  "images/Afactdeco.bmp",
  "images/Afactdoor.bmp",
  "images/Afactwall.bmp",
  "images/Ahlconsolea.bmp",
  "images/Ahlconsoleb.bmp",
  "images/Ahlsupport.bmp",
  "images/Ainlaida.bmp",
  "images/Ainlaidb.bmp",
  "images/Ainlaidc.bmp",
  "images/Alightrig.bmp",
  "images/Alwall1.bmp",
  "images/Alwall2.bmp",
  "images/Amachinepanela.bmp",
  "images/Amachinepanelb.bmp",
  "images/Anewroof.bmp",
  "images/Apfall.bmp",
  "images/Apowerunit.bmp",
  "images/Arigfan.bmp",
  "images/Arigspot.bmp",
  "images/Arigwall.bmp",
  "images/Ashwall.bmp",
  "images/Astevepipes.bmp",
  "images/Astola.bmp",
  "images/Astolb.bmp",
  "images/Asubw.bmp",
  "images/Atak.bmp",
  "images/Atend.bmp",
  "images/Atfront.bmp",
  "images/Awlrockwall.bmp",
};

#endif // IMGS_H
